"""empty message

Revision ID: 4c4470cba28d
Revises: b4d5aceadd36
Create Date: 2018-03-19 22:03:11.047501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4470cba28d'
down_revision = 'b4d5aceadd36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('daily_incentive_cents', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('total_incentive_cents', sa.Integer(), nullable=True))
    op.drop_column('tasks', 'incentive_cents')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('incentive_cents', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'total_incentive_cents')
    op.drop_column('tasks', 'daily_incentive_cents')
    # ### end Alembic commands ###
