"""empty message

Revision ID: 84976a1799c7
Revises: 43e4d949d49b
Create Date: 2018-05-10 09:34:44.878490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84976a1799c7'
down_revision = '43e4d949d49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
