"""empty message

Revision ID: 8e06082874d3
Revises: 84976a1799c7
Create Date: 2018-05-13 16:28:12.319994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e06082874d3'
down_revision = '84976a1799c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'fb_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'fb_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
