"""empty message

Revision ID: a70a32a64767
Revises: ab1600a0065d
Create Date: 2018-04-08 23:39:37.770740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a70a32a64767'
down_revision = 'ab1600a0065d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'due_date')
    # ### end Alembic commands ###
