"""empty message

Revision ID: ab1600a0065d
Revises: b3c6485126ab
Create Date: 2018-04-08 22:14:56.663693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab1600a0065d'
down_revision = 'b3c6485126ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'state')
    # ### end Alembic commands ###
