"""empty message

Revision ID: b3c6485126ab
Revises: 4c4470cba28d
Create Date: 2018-03-19 22:04:36.519391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3c6485126ab'
down_revision = '4c4470cba28d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('groups', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('tasks', 'updated_on')
    op.drop_column('tasks', 'created_on')
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.add_column('tasks', sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    op.drop_column('groups', 'updated_at')
    op.drop_column('groups', 'created_at')
    # ### end Alembic commands ###
