"""empty message

Revision ID: b4d5aceadd36
Revises: 0d8b89c2b41d
Create Date: 2018-03-19 21:43:31.761619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d5aceadd36'
down_revision = '0d8b89c2b41d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_group_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.add_column(u'tasks', sa.Column('buffer_days', sa.Integer(), nullable=True))
    op.add_column(u'tasks', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column(u'tasks', sa.Column('incentive_cents', sa.Integer(), nullable=True))
    op.add_column(u'tasks', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'tasks', 'updated_on')
    op.drop_column(u'tasks', 'incentive_cents')
    op.drop_column(u'tasks', 'created_on')
    op.drop_column(u'tasks', 'buffer_days')
    op.drop_table('user_group_association')
    op.drop_table('users')
    op.drop_table('groups')
    # ### end Alembic commands ###
