"""empty message

Revision ID: d5cf3629320c
Revises: 8e06082874d3
Create Date: 2018-06-14 01:25:28.080266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5cf3629320c'
down_revision = '8e06082874d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('group_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'group_id')
    # ### end Alembic commands ###
